/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.lemnisk.common.avro.model.event.page;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ContextUserAgent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 26904183378401851L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContextUserAgent\",\"namespace\":\"co.lemnisk.common.avro.model.event.page\",\"fields\":[{\"name\":\"deviceType\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"osType\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"osVersion\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"browser\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"ua\",\"type\":\"string\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContextUserAgent> ENCODER =
      new BinaryMessageEncoder<ContextUserAgent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContextUserAgent> DECODER =
      new BinaryMessageDecoder<ContextUserAgent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ContextUserAgent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ContextUserAgent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContextUserAgent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ContextUserAgent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ContextUserAgent from a ByteBuffer. */
  public static ContextUserAgent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence deviceType;
  @Deprecated public java.lang.CharSequence osType;
  @Deprecated public java.lang.CharSequence osVersion;
  @Deprecated public java.lang.CharSequence browser;
  @Deprecated public java.lang.CharSequence ua;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContextUserAgent() {}

  /**
   * All-args constructor.
   * @param deviceType The new value for deviceType
   * @param osType The new value for osType
   * @param osVersion The new value for osVersion
   * @param browser The new value for browser
   * @param ua The new value for ua
   */
  public ContextUserAgent(java.lang.CharSequence deviceType, java.lang.CharSequence osType, java.lang.CharSequence osVersion, java.lang.CharSequence browser, java.lang.CharSequence ua) {
    this.deviceType = deviceType;
    this.osType = osType;
    this.osVersion = osVersion;
    this.browser = browser;
    this.ua = ua;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deviceType;
    case 1: return osType;
    case 2: return osVersion;
    case 3: return browser;
    case 4: return ua;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deviceType = (java.lang.CharSequence)value$; break;
    case 1: osType = (java.lang.CharSequence)value$; break;
    case 2: osVersion = (java.lang.CharSequence)value$; break;
    case 3: browser = (java.lang.CharSequence)value$; break;
    case 4: ua = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'deviceType' field.
   * @return The value of the 'deviceType' field.
   */
  public java.lang.CharSequence getDeviceType() {
    return deviceType;
  }

  /**
   * Sets the value of the 'deviceType' field.
   * @param value the value to set.
   */
  public void setDeviceType(java.lang.CharSequence value) {
    this.deviceType = value;
  }

  /**
   * Gets the value of the 'osType' field.
   * @return The value of the 'osType' field.
   */
  public java.lang.CharSequence getOsType() {
    return osType;
  }

  /**
   * Sets the value of the 'osType' field.
   * @param value the value to set.
   */
  public void setOsType(java.lang.CharSequence value) {
    this.osType = value;
  }

  /**
   * Gets the value of the 'osVersion' field.
   * @return The value of the 'osVersion' field.
   */
  public java.lang.CharSequence getOsVersion() {
    return osVersion;
  }

  /**
   * Sets the value of the 'osVersion' field.
   * @param value the value to set.
   */
  public void setOsVersion(java.lang.CharSequence value) {
    this.osVersion = value;
  }

  /**
   * Gets the value of the 'browser' field.
   * @return The value of the 'browser' field.
   */
  public java.lang.CharSequence getBrowser() {
    return browser;
  }

  /**
   * Sets the value of the 'browser' field.
   * @param value the value to set.
   */
  public void setBrowser(java.lang.CharSequence value) {
    this.browser = value;
  }

  /**
   * Gets the value of the 'ua' field.
   * @return The value of the 'ua' field.
   */
  public java.lang.CharSequence getUa() {
    return ua;
  }

  /**
   * Sets the value of the 'ua' field.
   * @param value the value to set.
   */
  public void setUa(java.lang.CharSequence value) {
    this.ua = value;
  }

  /**
   * Creates a new ContextUserAgent RecordBuilder.
   * @return A new ContextUserAgent RecordBuilder
   */
  public static co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder newBuilder() {
    return new co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder();
  }

  /**
   * Creates a new ContextUserAgent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContextUserAgent RecordBuilder
   */
  public static co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder newBuilder(co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder other) {
    return new co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder(other);
  }

  /**
   * Creates a new ContextUserAgent RecordBuilder by copying an existing ContextUserAgent instance.
   * @param other The existing instance to copy.
   * @return A new ContextUserAgent RecordBuilder
   */
  public static co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder newBuilder(co.lemnisk.common.avro.model.event.page.ContextUserAgent other) {
    return new co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder(other);
  }

  /**
   * RecordBuilder for ContextUserAgent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContextUserAgent>
    implements org.apache.avro.data.RecordBuilder<ContextUserAgent> {

    private java.lang.CharSequence deviceType;
    private java.lang.CharSequence osType;
    private java.lang.CharSequence osVersion;
    private java.lang.CharSequence browser;
    private java.lang.CharSequence ua;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deviceType)) {
        this.deviceType = data().deepCopy(fields()[0].schema(), other.deviceType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.osType)) {
        this.osType = data().deepCopy(fields()[1].schema(), other.osType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.osVersion)) {
        this.osVersion = data().deepCopy(fields()[2].schema(), other.osVersion);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.browser)) {
        this.browser = data().deepCopy(fields()[3].schema(), other.browser);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ua)) {
        this.ua = data().deepCopy(fields()[4].schema(), other.ua);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ContextUserAgent instance
     * @param other The existing instance to copy.
     */
    private Builder(co.lemnisk.common.avro.model.event.page.ContextUserAgent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.deviceType)) {
        this.deviceType = data().deepCopy(fields()[0].schema(), other.deviceType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.osType)) {
        this.osType = data().deepCopy(fields()[1].schema(), other.osType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.osVersion)) {
        this.osVersion = data().deepCopy(fields()[2].schema(), other.osVersion);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.browser)) {
        this.browser = data().deepCopy(fields()[3].schema(), other.browser);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ua)) {
        this.ua = data().deepCopy(fields()[4].schema(), other.ua);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'deviceType' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeviceType() {
      return deviceType;
    }

    /**
      * Sets the value of the 'deviceType' field.
      * @param value The value of 'deviceType'.
      * @return This builder.
      */
    public co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder setDeviceType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.deviceType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceType' field has been set.
      * @return True if the 'deviceType' field has been set, false otherwise.
      */
    public boolean hasDeviceType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'deviceType' field.
      * @return This builder.
      */
    public co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder clearDeviceType() {
      deviceType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'osType' field.
      * @return The value.
      */
    public java.lang.CharSequence getOsType() {
      return osType;
    }

    /**
      * Sets the value of the 'osType' field.
      * @param value The value of 'osType'.
      * @return This builder.
      */
    public co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder setOsType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.osType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'osType' field has been set.
      * @return True if the 'osType' field has been set, false otherwise.
      */
    public boolean hasOsType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'osType' field.
      * @return This builder.
      */
    public co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder clearOsType() {
      osType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'osVersion' field.
      * @return The value.
      */
    public java.lang.CharSequence getOsVersion() {
      return osVersion;
    }

    /**
      * Sets the value of the 'osVersion' field.
      * @param value The value of 'osVersion'.
      * @return This builder.
      */
    public co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder setOsVersion(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.osVersion = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'osVersion' field has been set.
      * @return True if the 'osVersion' field has been set, false otherwise.
      */
    public boolean hasOsVersion() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'osVersion' field.
      * @return This builder.
      */
    public co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder clearOsVersion() {
      osVersion = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'browser' field.
      * @return The value.
      */
    public java.lang.CharSequence getBrowser() {
      return browser;
    }

    /**
      * Sets the value of the 'browser' field.
      * @param value The value of 'browser'.
      * @return This builder.
      */
    public co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder setBrowser(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.browser = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'browser' field has been set.
      * @return True if the 'browser' field has been set, false otherwise.
      */
    public boolean hasBrowser() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'browser' field.
      * @return This builder.
      */
    public co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder clearBrowser() {
      browser = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'ua' field.
      * @return The value.
      */
    public java.lang.CharSequence getUa() {
      return ua;
    }

    /**
      * Sets the value of the 'ua' field.
      * @param value The value of 'ua'.
      * @return This builder.
      */
    public co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder setUa(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.ua = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'ua' field has been set.
      * @return True if the 'ua' field has been set, false otherwise.
      */
    public boolean hasUa() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'ua' field.
      * @return This builder.
      */
    public co.lemnisk.common.avro.model.event.page.ContextUserAgent.Builder clearUa() {
      ua = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContextUserAgent build() {
      try {
        ContextUserAgent record = new ContextUserAgent();
        record.deviceType = fieldSetFlags()[0] ? this.deviceType : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.osType = fieldSetFlags()[1] ? this.osType : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.osVersion = fieldSetFlags()[2] ? this.osVersion : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.browser = fieldSetFlags()[3] ? this.browser : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.ua = fieldSetFlags()[4] ? this.ua : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContextUserAgent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContextUserAgent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContextUserAgent>
    READER$ = (org.apache.avro.io.DatumReader<ContextUserAgent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
